# Dockerfile

# Start with a Python base image
FROM python:3.11

# Set the working directory in the container
WORKDIR /app

# Copy the project files into the container
COPY . /app

# Install the dependencies from requirements.txt
RUN pip install -r requirements.txt

# Expose the port for Streamlit
EXPOSE 8501

# Copy the entrypoint script and make it executable
COPY entrypoint.sh /app/entrypoint.sh
RUN chmod +x /app/entrypoint.sh

# Set the entrypoint
ENTRYPOINT ["/app/entrypoint.sh"]
