services:
  db:
    image: postgres
    container_name: postgres_db
    environment:
      POSTGRES_USER: jaber
      POSTGRES_PASSWORD: 13711992
      POSTGRES_DB: stock_data
    networks:
      - stock_network
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U jaber"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: stock_dashboard
    environment:
      - DATABASE_URL=postgresql://jaber:13711992@db:5432/stock_data
    networks:
      - stock_network
    ports:
      - "8501:8501"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app  # Optional: Mounts the current directory to /app in the container for development

networks:
  stock_network:
    driver: bridge
